import pandas as pd
import matplotlib.pyplot as plt
import os
os.makedirs("images", exist_ok=True)

df = pd.read_csv("Dataset/Superstore Sales Data.csv")

# ===================== Data Exploration =======================
print(df.head())

#How many no of rows and columns are in the data?
print("\nNo of rows and columns in the data: ",df.shape)

#Check column names
print("\nColumn names of the dataset:\n ",df.columns)

#Get Information about every column
print("\nInformation about every Column:\n")
df.info()

#Define Statistical summary
print("\nStatistical Summary: \n",df.describe())

#Checking Cardinality/Unique Rows in each column
print("\nNumber of Unique Rows in the Dataset:\n",df.nunique())

#Check for any missing value:
print("\nCheck for Missing values:\n",df.isnull().sum())

#Check for any duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# ===================== Data Cleaning =======================

# convert Order dates to pandas datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')

# convert shipping dates to pandas datetime format
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

# ================= Feature Engineering ======================

#Creating new order year, month, quater columns from order date
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month_name()
df["Order Month Number"] = df["Order Date"].dt.month
df["Quarter"] = df["Order Date"].dt.quarter

#Counting Shipping Days for each order
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

#GConvert Order Date in Weekday and Weekday Number
df["Weekday Number"] = df["Order Date"].dt.dayofweek
df["Weekday"] = df["Order Date"].dt.day_name()

#Function to display sales value in a specified format
def show_sales(values):
    def formatter(pct):
        total = sum(values)
        value = pct * total / 100
        return f"${value:,.0f}\n({pct:.1f}%)"
    return formatter

#Function to save the plot in a folder
def save_plot(filename):
    plt.tight_layout()
    plt.savefig(
        f"images/{filename}",
        dpi=300,
        bbox_inches="tight"
    )
    plt.show()
    plt.close()
    
# ============= Exploratory Data Analysis ====================

# ====================== Category ============================

# Business Question: Which category has the most orders?
no_of_orders = df.groupby("Category")["Order ID"].nunique().sort_values(ascending= False)
print(f"\nNumber of Orders by Category: {no_of_orders}\n")

# Business Question: What is the average sales generated by the categories?
#Average sales by Category
average_sales = (
    df.groupby("Category")["Sales"]
      .mean()
      .sort_values(ascending= False)
      .round(2)
)
print(f"\nAverage Sales by Category: {average_sales}\n")

# Business Question: Which Category generated the highest sales?
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending= False)
category_sales = category_sales.reset_index()

sales = category_sales["Sales"]
categories = category_sales["Category"]
explode = (0.05,0.05,0.05)

fig, ax = plt.subplots(figsize=(10,5))    

ax.pie(sales, labels = categories, autopct=show_sales(sales),  startangle = 90, explode=explode, shadow=True)
ax.axis('equal')  
plt.title(f"Sales by Category\n ${sum(category_sales["Sales"]):,.0f}", fontsize = 15)
save_plot("sales_generated_by_category.png")

# ================== Sub Category ============================

# Business Question: Which sub category generated the highest sales?
sub_category_sales = df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending= False).sort_values()

sub_category_sales = sub_category_sales.reset_index()

plt.figure(figsize = (10,5))
plt.barh(sub_category_sales["Sub-Category"],sub_category_sales["Sales"], edgecolor = "black", linewidth = 1)
plt.title(f"Sales by Sub Category\n ${sum(sub_category_sales["Sales"]):,.0f}", fontsize = 15)
plt.xlabel("Sales", fontsize = 10)
plt.ylabel("Sub Category", fontsize = 10)
plt.xticks(fontsize = 8)
plt.yticks(fontsize = 8)

for index, value in enumerate(sub_category_sales["Sales"]):
    plt.text(value + 1000, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("sales_generated_by_subcategory.png")

# ====================== Segment ============================

# Business Question: Which segment generated the highest sales?
segment_sales = df.groupby('Segment')['Sales'].sum().sort_values(ascending=False)
segment_sales = segment_sales.round(2).reset_index()

sales = segment_sales["Sales"]
labels = segment_sales["Segment"]

plt.figure(figsize = (10,5))
explode = [0.05,0.05,0.05]
plt.pie(sales, labels = labels, explode = explode, shadow = True, startangle = 90, autopct= show_sales(sales))
ax.axis('equal')  
plt.title(f"Sales by Segments\n ${sum(segment_sales["Sales"]):,.0f}", fontsize = 15)
save_plot("sales_generated_by_segment.png")

# ================== Shipping Mode ==========================

# Business Question: What is the average shipping days for different shipping mode?
average_shipping_days = df.groupby("Ship Mode")["Shipping Days"].mean()
print(f"\nAverage Shipping Days by Category: {average_shipping_days}\n")

# Business Question: Which shipping mode generated the highest sales?
shipping_mode_sales = df.groupby('Ship Mode')['Sales'].sum().sort_values(ascending=False)
shipping_mode_sales = shipping_mode_sales.round(2).reset_index()

sales = shipping_mode_sales["Sales"]
labels = shipping_mode_sales["Ship Mode"]
explode = [0.05] * len(shipping_mode_sales)

fig, ax = plt.subplots(figsize = (10,5))
wedges, texts, autotexts = ax.pie(sales, labels = labels, explode = explode, shadow = True, startangle = 90, autopct= show_sales(sales))
plt.title(f"Sales by Shipping Mode \n ${sum(shipping_mode_sales["Sales"]):,.0f}", fontsize = 15)
plt.setp(autotexts, fontsize=8)
plt.setp(texts, fontsize=10)
save_plot("sales_generated_by_shipping_mode.png")

# ====================== Region ============================

# Business Question: Which region generated the highest sales?
region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
region_sales = region_sales.round(2).reset_index()

plt.figure(figsize = (10,5))
plt.bar(region_sales['Region'], region_sales["Sales"], edgecolor='black', linewidth = 1)
plt.title(f"Sales by Region\n ${sum(region_sales["Sales"]):,.0f}", fontsize = 15)
plt.xlabel("Region",fontsize = 10)
plt.ylabel("Sales",fontsize = 10)
plt.xticks(fontsize = 8)
plt.yticks(fontsize = 8)

for k, v in region_sales["Sales"].items():
    if v > 300000:
        plt.text(k,v-150000,'$'+ str(v), fontsize=8,rotation=90,color='k', horizontalalignment='center');
    else:
        plt.text(k,v+5000,'$'+ str(v), fontsize=8,rotation=90,color='k', horizontalalignment='center');

save_plot("sales_generated_by_region.png")

# =================== States & Cities =========================

# Business Question: Which states generated the highest sales?
state_sales = df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(10).sort_values()
state_sales = state_sales.round(2).reset_index()

plt.figure(figsize = (10,5)) 
plt.title("Top 10 States by Sales", fontsize=15) 
plt.barh(state_sales["State"], state_sales["Sales"], edgecolor='black', linewidth = 1)
plt.xlabel("Sales",fontsize=10)  
plt.ylabel("States",fontsize=10) 
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)

for index, value in enumerate(state_sales["Sales"]):
    plt.text(value + 1000, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("sales_generated_by_states.png")

# Business Question: Which cities generated the highest sales?
city_sales = df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(10).sort_values()
city_sales = city_sales.round(2).reset_index()

plt.figure(figsize = (10,5))
plt.barh(city_sales['City'], city_sales["Sales"], edgecolor='black', linewidth = 1)
plt.title("Top 10 Cities by Sales", fontsize = 15)
plt.xlabel("Sales",fontsize = 10)
plt.ylabel("Cities",fontsize = 10)
plt.xticks(fontsize = 8)
plt.yticks(fontsize = 8)

for index, value in enumerate(city_sales["Sales"]):
    plt.text(value + 1000, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("sales_generated_by_cities.png")

# ================ Monthly Sales & Order Trend =========================

# Business Question: What does the Monthly sales and order Trend looks like?
monthly_sales = (
    df.groupby(["Order Month Number", "Order Month"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Order Month Number")
)

plt.figure(figsize=(10,5))
plt.plot(monthly_sales["Order Month"], monthly_sales["Sales"], marker="o")

plt.title("Monthly Sales Trend", fontsize = 15)
plt.xlabel("Month", fontsize = 10)
plt.ylabel("Sales", fontsize = 10)
plt.xticks(rotation=45, fontsize = 8)
plt.grid(axis="y", alpha=0.3)
save_plot("monthly_sales_trend.png")

#Monthly Order trend
monthly_orders = (
    df.groupby(["Order Month Number", "Order Month"])["Order ID"]
      .nunique()
      .reset_index()
      .sort_values("Order Month Number")
)
plt.figure(figsize=(10,5))
plt.plot(
    monthly_orders["Order Month"],
    monthly_orders["Order ID"],
    marker="o"
)

plt.title("Monthly Orders Trend", fontsize = 15)
plt.xlabel("Month", fontsize = 10)
plt.ylabel("Number of Orders", fontsize = 10)
plt.grid(axis="y", alpha=0.3)
save_plot("monthly_order_trend.png")

# ================ Yearly Sales Trend ==========================

# Business Question: How does the yearly sales trend look like?
yearly_sales = (
    df.groupby("Order Year")["Sales"]
      .sum()
)

plt.figure(figsize=(10,5))
plt.plot(yearly_sales.index,
         yearly_sales.values,
         marker="o")

plt.title("Yearly Sales Trend", fontsize = 15)
plt.xlabel("Year", fontsize = 10)
plt.ylabel("Sales", fontsize = 10)
plt.xticks(yearly_sales.index, fontsize = 8)
plt.grid(axis="y", alpha=0.3)
save_plot("yearly_sales_trend.png")

# ================ Quaterly Sales Trend ========================

# Business Question: How does the quarterly sales trend look like?
quarterly_sales = (
    df.groupby("Quarter")["Sales"]
      .sum()
)

plt.figure(figsize=(8,5))
plt.bar(
    quarterly_sales.index.astype(str),
    quarterly_sales.values
)

plt.title("Quarterly Sales Trend", fontsize = 15)
plt.xlabel("Quarter", fontsize = 10)
plt.ylabel("Sales", fontsize = 10)
plt.grid(axis="y", alpha=0.3)
save_plot("quaterly_sales_trend.png")

# ================ Sales By Weekday ==========================

# Business Question: How does the sales look like on weekdays?
weekly_sales = (
    df.groupby(["Weekday Number", "Weekday"])["Sales"]
      .sum()
      .reset_index()
      .sort_values("Weekday Number")
)

plt.figure(figsize=(10,5))
plt.bar(
    weekly_sales["Weekday"].values,
    weekly_sales["Sales"].values,
    edgecolor="black"
)

plt.title("Sales by Weekday", fontsize = 15)
plt.xlabel("Weekday", fontsize = 10)
plt.ylabel("Sales", fontsize = 10)
plt.grid(axis="y", alpha=0.3)
save_plot("sales_by_weekday.png")

# ====================== Customers ============================

# Business Question: Which customer generated the highest sales?
customer_sales = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10).sort_values()
customer_sales = customer_sales.round(2).reset_index()

plt.figure(figsize = (10,5)) 
plt.title("Top 10 Customers by Sales", fontsize=15) 
plt.barh(customer_sales["Customer Name"], customer_sales["Sales"], edgecolor='black', linewidth = 1)
plt.xlabel("Sales",fontsize=10)  
plt.ylabel("Customers",fontsize=10) 
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)

for index, value in enumerate(customer_sales["Sales"]):
    plt.text(value + 500, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("top_10_customers_by_sales.png")

# Business Question: Which customer has placed the most orders?
top_order_customers = (
    df.groupby("Customer Name")["Order ID"]
      .nunique()
      .sort_values(ascending=False)
      .head(10).sort_values()
      .reset_index()
)

plt.figure(figsize=(10,5))
plt.barh(
    top_order_customers["Customer Name"],
    top_order_customers["Order ID"],
    edgecolor="black"
)

plt.title("Top 10 Customers by Total Number of Order", fontsize = 15)
plt.xlabel("Number of Orders", fontsize = 8)
plt.ylabel("Customer", fontsize = 8)

for index, value in enumerate(top_order_customers["Order ID"]):
    plt.text(value +0.25, index, f"{value:,.0f}", va="center", fontsize=6)

save_plot("top_10_customers_by_no_of_orders.png")

# ====================== Product ============================

# Business Question: Which Products generated the highest sales?
top_products = df.groupby("Product Name")["Sales"].sum().sort_values(ascending= False).head(10).sort_values()
top_products = top_products.reset_index()

plt.figure(figsize = (10,5))
plt.barh(top_products["Product Name"],top_products["Sales"], edgecolor = "black", linewidth = 1)
plt.title("Top 10 Products by Sales", fontsize = 15)
plt.xlabel("Sales", fontsize = 10)
plt.ylabel("Product Name", fontsize = 10)
plt.xticks(fontsize = 8)
plt.yticks(fontsize = 8)

for index, value in enumerate(top_products["Sales"]):
    plt.text(value + value*0.02, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("top_10_products.png")

# Business Question: Which Product generated the lowest sales?
bottom_products = df.groupby("Product Name")["Sales"].sum().sort_values(ascending= False).tail(10).sort_values()
bottom_products = bottom_products.reset_index()

plt.figure(figsize = (10,5))
plt.barh(bottom_products["Product Name"],bottom_products["Sales"], edgecolor = "black", linewidth = 1)
plt.title("Bottom 10 Products by Sales", fontsize = 15)
plt.xlabel("Sales", fontsize = 10)
plt.ylabel("Product Name", fontsize = 10)
plt.xticks(fontsize = 8)
plt.yticks(fontsize = 8)

for index, value in enumerate(bottom_products["Sales"]):
    plt.text(value + 0.15, index, f"${value:,.0f}", va="center", fontsize=6)

save_plot("bottom_10_products.png")

# ================ Average Shipping Days =======================

# Business Question: What is the average shipping days for all the orders?
average_days = df["Shipping Days"].mean()
print(f"Average Shipping Days: {average_days:.2f}")\

plt.figure(figsize=(10,5))
plt.hist(df["Shipping Days"], bins=40)
plt.title("Distribution of Shipping Days", fontsize = 15)
plt.xlabel("Shipping Days", fontsize = 10)
plt.ylabel("Number of Orders", fontsize = 10)
plt.grid(axis="y", alpha=0.3)
save_plot("average_shipping_days.png")

# =========== Sales Distribution & Box Plot =========================

# Business Question: How does the Sales Distribution look like?
plt.figure(figsize=(10,5))
plt.hist(df["Sales"], bins=40)
plt.xlim(0, 5000)       #limiting to 0 to 5000 sales value only
plt.title("Sales Distribution (0–5000)", fontsize = 15)
plt.xlabel("Sales", fontsize = 10)
plt.ylabel("Frequency", fontsize = 10)
save_plot("sales_distribution.png")

plt.figure(figsize=(10,5))
plt.boxplot(df["Sales"], vert=False)
plt.title("Sales Box Plot", fontsize = 15)
save_plot("sales_box_plot.png")

print("=" * 50)
print("SUMMARY")
print("=" * 50)

print(f"Highest Sales Category : {category_sales.iloc[0]['Category']}")
print(f"Highest Sales Region   : {region_sales.iloc[0]['Region']}")
print(f"Highest Sales State    : {state_sales.iloc[0]['State']}")
print(f"Highest Sales City     : {city_sales.iloc[0]['City']}")
print(f"Highest Sales Customer : {customer_sales.iloc[0]['Customer Name']}")
print(f"Highest Sales Product  : {top_products.iloc[0]['Product Name']}")
print(f"Average Shipping Days  : {average_days:.2f}")
